package entity

type ShipOrder struct {
	ReceiveSkcNum                int    `json:"receiveSkcNum"`
	ExpressPackageNum            int    `json:"expressPackageNum"`
	LatestFeedbackStatus         int    `json:"latestFeedbackStatus"`
	ExpectLatestPickTime         any    `json:"expectLatestPickTime"`
	DeliveryOrderCancelLeftTime  any    `json:"deliveryOrderCancelLeftTime"`
	ExpressDeliverySn            string `json:"expressDeliverySn"`
	DeliveryAddressID            any    `json:"deliveryAddressId"`
	ExpressWeightFeedbackStatus  int    `json:"expressWeightFeedbackStatus"`
	ExpressRejectStatus          any    `json:"expressRejectStatus"`
	PackageReceiveInfoVOList     any    `json:"packageReceiveInfoVOList"`
	TaxWarehouseApplyOperateType int    `json:"taxWarehouseApplyOperateType"`
	ProductSkcID                 int64  `json:"productSkcId"`
	SkcExtCode                   string `json:"skcExtCode"`
	InboundTime                  any    `json:"inboundTime"`
	SubWarehouseID               int64  `json:"subWarehouseId"`
	PackageList                  []struct {
		SkcNum    int    `json:"skcNum"`
		PackageSn string `json:"packageSn"`
	} `json:"packageList"`
	InventoryRegion             int    `json:"inventoryRegion"`
	DeliverPackageNum           int    `json:"deliverPackageNum"`
	DriverName                  string `json:"driverName"`
	SubPurchaseOrderSn          string `json:"subPurchaseOrderSn"`
	ExpressCompanyID            int    `json:"expressCompanyId"`
	DefectiveSkcNum             int    `json:"defectiveSkcNum"`
	Status                      int    `json:"status"`
	ExpectPickUpGoodsTime       int    `json:"expectPickUpGoodsTime"`
	PredictTotalPackageWeight   int    `json:"predictTotalPackageWeight"`
	SupplierID                  int64  `json:"supplierId"`
	IsDisplayCourier            bool   `json:"isDisplayCourier"`
	IsCustomProduct             bool   `json:"isCustomProduct"`
	DeliveryMethod              int    `json:"deliveryMethod"`
	ExpressWeightFeedbackTip    any    `json:"expressWeightFeedbackTip"`
	ExceptionFeedBackTotalCount any    `json:"exceptionFeedBackTotalCount"`
	OtherDeliveryPackageNum     int    `json:"otherDeliveryPackageNum"`
	PurchaseStockType           int    `json:"purchaseStockType"`
	IfCanOperateDeliver         bool   `json:"ifCanOperateDeliver"`
	ReceivePackageNum           int    `json:"receivePackageNum"`
	IsPrintBoxMark              bool   `json:"isPrintBoxMark"`
	ExpressCompany              string `json:"expressCompany"`
	IsClothCategory             bool   `json:"isClothCategory"`
	DeliveryOrderSn             string `json:"deliveryOrderSn"`
	DeliverTime                 any    `json:"deliverTime"`
	UrgencyType                 int    `json:"urgencyType"`
	ExpressBatchSn              string `json:"expressBatchSn"`
	ReceiveAddressInfo          struct {
		DistrictCode  int64  `json:"districtCode"`
		CityName      string `json:"cityName"`
		DistrictName  string `json:"districtName"`
		Phone         string `json:"phone"`
		ProvinceCode  int64  `json:"provinceCode"`
		CityCode      int64  `json:"cityCode"`
		ReceiverName  string `json:"receiverName"`
		DetailAddress string `json:"detailAddress"`
		ProvinceName  string `json:"provinceName"`
	} `json:"receiveAddressInfo"`
	PlateNumber       string `json:"plateNumber"`
	ReceiveTime       any    `json:"receiveTime"`
	PackageDetailList []struct {
		ProductSkuID         int64 `json:"productSkuId"`
		ProductOriginalSkuID any   `json:"productOriginalSkuId"`
		PersonalText         any   `json:"personalText"`
		SkuNum               int   `json:"skuNum"`
	} `json:"packageDetailList"`
	SubPurchaseOrderBasicVO struct {
		SupplierID         int64  `json:"supplierId"`
		IsCustomProduct    bool   `json:"isCustomProduct"`
		ProductSkcPicture  string `json:"productSkcPicture"`
		IsFirst            bool   `json:"isFirst"`
		PurchaseStockType  int    `json:"purchaseStockType"`
		IsClothCategory    any    `json:"isClothCategory"`
		ProductSkcID       int64  `json:"productSkcId"`
		SettlementType     int    `json:"settlementType"`
		SkcExtCode         string `json:"skcExtCode"`
		SubWarehouseID     any    `json:"subWarehouseId"`
		UrgencyType        int    `json:"urgencyType"`
		FragileTag         bool   `json:"fragileTag"`
		PurchaseQuantity   int    `json:"purchaseQuantity"`
		SubWarehouseName   any    `json:"subWarehouseName"`
		PurchaseTime       int64  `json:"purchaseTime"`
		SubPurchaseOrderSn string `json:"subPurchaseOrderSn"`
	} `json:"subPurchaseOrderBasicVO"`
	SubWarehouseName        string `json:"subWarehouseName"`
	PurchaseTime            int64  `json:"purchaseTime"`
	SkcPurchaseNum          int    `json:"skcPurchaseNum"`
	DeliverSkcNum           int    `json:"deliverSkcNum"`
	DeliveryOrderCreateTime int64  `json:"deliveryOrderCreateTime"`
}
